Repository arangodb/arangojs, pull requests merged in 2018-09, with the labels that each got.

#568 Support nesting of aql queries
  CHANGELOG.md
  src/aql-query.ts
  src/test/05-aql-queries.ts
Labels: enhancement

#571 Be more explicit about version compat
  CHANGELOG.md
  docs/Drivers/JS/GettingStarted/README.md
  docs/Drivers/JS/README.md
  docs/Drivers/JS/Reference/Collection/CollectionManipulation.md
  docs/Drivers/JS/Reference/Collection/DocumentCollection.md
  docs/Drivers/JS/Reference/Collection/DocumentManipulation.md
  docs/Drivers/JS/Reference/Collection/EdgeCollection.md
  docs/Drivers/JS/Reference/Collection/Indexes.md
  docs/Drivers/JS/Reference/Collection/README.md
  docs/Drivers/JS/Reference/Collection/SimpleQueries.md
  docs/Drivers/JS/Reference/Cursor.md
  docs/Drivers/JS/Reference/Database/DatabaseManipulation.md
  docs/Drivers/JS/Reference/Database/FoxxServices.md
  docs/Drivers/JS/Reference/Database/Queries.md
  docs/Drivers/JS/Reference/Database/README.md
  docs/Drivers/JS/Reference/Database/Transactions.md
  docs/Drivers/JS/Reference/Database/ViewAccess.md
  docs/Drivers/JS/Reference/ViewManipulation.md
Labels: documentation

#569 Add dirtyRead support
  src/connection.ts
  src/database.ts
  src/test/99-load-balancing.ts
  src/util/request.node.ts
Labels: arangodb, enhancement

#574 Fix allowDirtyRead for cursor#next
  src/cursor.ts
  src/database.ts
  src/test/99-load-balancing.ts
Labels: bug
